[32m2025-01-17 14:12:08 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - 5494 - LOGS_CAPTURED - Started capturing logs in process (pid: 5494).
[32m2025-01-17 14:12:08 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - 5494 - dbt_analytics - STEP_START - Started execution of step "dbt_analytics".
[32m2025-01-17 14:12:08 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['db_postgres.scores_movies_users']`.
[32m2025-01-17 14:12:08 -0600[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - dbt_analytics - An error was encountered when creating a handle to the dbt adapter in Dagster.
Traceback (most recent call last):
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster_dbt/core/resource.py", line 672, in cli
    adapter = self._initialize_adapter(cli_vars)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster_dbt/core/resource.py", line 364, in _initialize_adapter
    profile = load_profile(self.project_dir, cli_vars, self.profile, self.target)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/runtime.py", line 71, in load_profile
    profile = Profile.render(
              ^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/profile.py", line 403, in render
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/profile.py", line 360, in from_raw_profiles
    raise DbtProjectError("Could not find profile named '{}'".format(profile_name))
dbt.exceptions.DbtProjectError: Runtime Error
  Could not find profile named 'db_postgres'
[32m2025-01-17 14:12:08 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - dbt_analytics - Copying `/Users/ari/Desktop/github_repos/db_postgres/target/partial_parse.msgpack` to `/Users/ari/Desktop/github_repos/db_postgres/target/dbt_analytics-6d55989-f1e27ec/partial_parse.msgpack` to take advantage of partial parsing.
[32m2025-01-17 14:12:08 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - dbt_analytics - Running dbt command: `dbt run --select db_postgres.scores_movies_users`.
[32m2025-01-17 14:12:11 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - 5494 - dbt_analytics - STEP_OUTPUT - Yielded output "scores_movies_users" of type "Nothing". (Type check passed).
[32m2025-01-17 14:12:11 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - 5494 - dbt_analytics - ASSET_MATERIALIZATION - Materialized value scores_movies_users.
[32m2025-01-17 14:12:11 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - dbt_analytics - Finished dbt command: `dbt run --select db_postgres.scores_movies_users`.
[32m2025-01-17 14:12:11 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 6d559896-98e6-4d76-8426-1d40ba7bfe30 - 5494 - dbt_analytics - STEP_SUCCESS - Finished execution of step "dbt_analytics" in 3.24s.
